### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by SerZhyAle** [mike9251/simswap-inference-pytorch#25]
(sink2) C:\_N\simswap-inference-pytorch-main>python app.py --config-name=run_image.yaml
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\_N\simswap-inference-pytorch-main\app.py", line 74, in <module>
    main()
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\_N\simswap-inference-pytorch-main\app.py", line 68, in main
    app = Application(config)
  File "C:\_N\simswap-inference-pytorch-main\app.py", line 49, in __init__
    self.model = SimSwap(
  File "C:\_N\simswap-inference-pytorch-main\src\simswap.py", line 42, in __init__
    self.set_parameters(config)
  File "C:\_N\simswap-inference-pytorch-main\src\simswap.py", line 118, in set_parameters
    self.set_smooth_mask_kernel_size(config.smooth_mask_kernel_size)
  File "C:\_N\simswap-inference-pytorch-main\src\simswap.py", line 169, in set_smooth_mask_kernel_size
    self.re_initialize_soft_mask()
  File "C:\_N\simswap-inference-pytorch-main\src\simswap.py", line 160, in re_initialize_soft_mask
    self.smooth_mask = SoftErosion(kernel_size=self.smooth_mask_kernel_size,
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\torch\nn\modules\module.py", line 688, in _apply
    self._buffers[key] = fn(buf)
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\_N\Anaconda3\envs\sink2\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(sink2) C:\_N\simswap-inference-pytorch-main>

**Comment by morisuba** [comment]
i too get the same error

**Comment by vizsumit** [comment]
getting same error
