### ISSUE TITLE
Always error when video finishing compile image, Hydra.

### ISSUE THREAD

**Issue by poepoeng** [mike9251/simswap-inference-pytorch#32]
when finishing image compile to video, always got this error.

`
Error executing job with overrides: []
Traceback (most recent call last):
  File "/ironman/simswap-inference-pytorch/app.py", line 70, in main
    app.run()
  File "/ironman/simswap-inference-pytorch/app.py", line 60, in run
    output = self.model(att_img)
  File "/ironman/simswap-inference-pytorch/src/simswap.py", line 230, in __call__
    align_att_imgs, att_transforms, att_detection_score = self.run_detect_align(
  File "/ironman/simswap-inference-pytorch/src/simswap.py", line 186, in run_detect_align
    detection: Detection = self.face_detector(image)
  File "/ironman/simswap-inference-pytorch/src/FaceDetector/face_detector.py", line 31, in __call__
    bboxes, kpss = self.handler.detect(
  File "/usr/local/lib/python3.9/dist-packages/insightface/model_zoo/scrfd.py", line 204, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
`

but when i change to another video, sometimes its work. please fix this.

**Comment by Cacha21** [comment]
I'm having the same issue. Did you find a fix ??
